"""dummy

Revision ID: 059c2c6fb0bf
Revises: d232c60204c1
Create Date: 2020-09-04 16:42:29.790551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059c2c6fb0bf'
down_revision = 'd232c60204c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Frequency', sa.Integer(), nullable=True),
    sa.Column('Kanji', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy')
    # ### end Alembic commands ###
