"""kanji

Revision ID: 2790f5da7ecb
Revises: 71d5f177d642
Create Date: 2020-08-27 15:51:05.268009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2790f5da7ecb'
down_revision = '71d5f177d642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanji',
    sa.Column('Order', sa.Integer(), nullable=False),
    sa.Column('Frequency', sa.String(length=32), nullable=True),
    sa.Column('Kanji', sa.String(length=32), nullable=True),
    sa.Column('Type', sa.String(length=32), nullable=True),
    sa.Column('Meaning1', sa.String(length=32), nullable=True),
    sa.Column('Meaning2', sa.String(length=32), nullable=True),
    sa.Column('Meaning3', sa.String(length=32), nullable=True),
    sa.Column('Radical1', sa.String(length=32), nullable=True),
    sa.Column('Radical2', sa.String(length=32), nullable=True),
    sa.Column('Radical3', sa.String(length=32), nullable=True),
    sa.Column('Radical4', sa.String(length=32), nullable=True),
    sa.Column('Onyomi_Reading1', sa.String(length=32), nullable=True),
    sa.Column('Onyomi_Reading2', sa.String(length=32), nullable=True),
    sa.Column('Kunyomi_Reading1', sa.String(length=32), nullable=True),
    sa.Column('Kunyomi_Reading2', sa.String(length=32), nullable=True),
    sa.Column('Mnemonic', sa.String(length=256), nullable=True),
    sa.Column('Notes', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('Order')
    )
    op.drop_table('kanjidata')
    op.drop_table('kanji_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanji_data',
    sa.Column('Order', sa.INTEGER(), nullable=False),
    sa.Column('Frequency', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Kanji', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Meaning1', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Meaning2', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Meaning3', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Radical1', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Radical2', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Radical3', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Radical4', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Onyomi_Reading1', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Onyomi_Reading2', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Kunyomi_Reading1', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Kunyomi_Reading2', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Mnemonic', sa.VARCHAR(length=32), nullable=True),
    sa.Column('Notes', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('Order')
    )
    op.create_table('kanjidata',
    sa.Column('Order1', sa.INTEGER(), nullable=True),
    sa.Column('Frequency1', sa.INTEGER(), nullable=True),
    sa.Column('Kanji1', sa.TEXT(), nullable=True),
    sa.Column('Type1', sa.TEXT(), nullable=True),
    sa.Column('Meaning1', sa.TEXT(), nullable=True),
    sa.Column('Meaning2', sa.TEXT(), nullable=True),
    sa.Column('Meaning3', sa.TEXT(), nullable=True),
    sa.Column('Radical1', sa.TEXT(), nullable=True),
    sa.Column('Radical2', sa.TEXT(), nullable=True),
    sa.Column('Radical3', sa.TEXT(), nullable=True),
    sa.Column('Radical4', sa.TEXT(), nullable=True),
    sa.Column('Onyomi Reading1', sa.TEXT(), nullable=True),
    sa.Column('Onyomi Reading2', sa.TEXT(), nullable=True),
    sa.Column('Kunyomi Reading1', sa.TEXT(), nullable=True),
    sa.Column('Kunyomi Reading2', sa.TEXT(), nullable=True),
    sa.Column('Mnemonic', sa.TEXT(), nullable=True),
    sa.Column('Notes', sa.TEXT(), nullable=True)
    )
    op.drop_table('kanji')
    # ### end Alembic commands ###
