"""kanji table

Revision ID: 71d5f177d642
Revises: c3abb2e4772d
Create Date: 2020-08-22 22:10:37.069871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d5f177d642'
down_revision = 'c3abb2e4772d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanji_data',
    sa.Column('Order', sa.Integer(), nullable=False),
    sa.Column('Frequency', sa.String(length=32), nullable=True),
    sa.Column('Kanji', sa.String(length=32), nullable=True),
    sa.Column('Type', sa.String(length=32), nullable=True),
    sa.Column('Meaning1', sa.String(length=32), nullable=True),
    sa.Column('Meaning2', sa.String(length=32), nullable=True),
    sa.Column('Meaning3', sa.String(length=32), nullable=True),
    sa.Column('Radical1', sa.String(length=32), nullable=True),
    sa.Column('Radical2', sa.String(length=32), nullable=True),
    sa.Column('Radical3', sa.String(length=32), nullable=True),
    sa.Column('Radical4', sa.String(length=32), nullable=True),
    sa.Column('Onyomi_Reading1', sa.String(length=32), nullable=True),
    sa.Column('Onyomi_Reading2', sa.String(length=32), nullable=True),
    sa.Column('Kunyomi_Reading1', sa.String(length=32), nullable=True),
    sa.Column('Kunyomi_Reading2', sa.String(length=32), nullable=True),
    sa.Column('Mnemonic', sa.String(length=128), nullable=True),
    sa.Column('Notes', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kanji_data')
    # ### end Alembic commands ###
