"""mnemonics table

Revision ID: b4bb255960e9
Revises: f9cabb89eb81
Create Date: 2020-11-07 19:12:25.007333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bb255960e9'
down_revision = 'f9cabb89eb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_mnemonics',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Mnemonic', sa.String(length=512), nullable=True),
    sa.Column('User', sa.Integer(), nullable=True),
    sa.Column('Kanji', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Kanji'], ['kanji_data.Id'], ),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_column('user', 'last_login_attemp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_attemp', sa.DATETIME(), nullable=True))
    op.drop_table('custom_mnemonics')
    # ### end Alembic commands ###
