"""ID Bushu

Revision ID: d232c60204c1
Revises: 8dc5edd99471
Create Date: 2020-09-03 21:13:27.669153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd232c60204c1'
down_revision = '8dc5edd99471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanji_data',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Frequency', sa.Integer(), nullable=True),
    sa.Column('Kanji', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Type', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Meaning1', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Meaning2', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Meaning3', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Bushu1', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Bushu2', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Bushu3', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Bushu4', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Radical1', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Radical2', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Radical3', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Radical4', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Onyomi_Reading1', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Onyomi_Reading2', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Kunyomi_Reading1', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Kunyomi_Reading2', sa.String(length=32, collation='NOCASE'), nullable=True),
    sa.Column('Mnemonic', sa.String(length=256), nullable=True),
    sa.Column('Notes', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kanji_data')
    # ### end Alembic commands ###
