"""custom notes

Revision ID: e101c5205be2
Revises: b4bb255960e9
Create Date: 2020-12-04 09:16:50.021883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e101c5205be2'
down_revision = 'b4bb255960e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_notes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Notes', sa.String(length=512), nullable=True),
    sa.Column('User', sa.String(length=256), nullable=True),
    sa.Column('Kanji', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Kanji'], ['kanji_data.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('custom_mnemonics')
    op.drop_column('user', 'last_login_attemp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_mnemonics',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Mnemonic', sa.VARCHAR(length=512), nullable=True),
    sa.Column('User', sa.INTEGER(), nullable=True),
    sa.Column('Kanji', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['Kanji'], ['kanji_data.Id'], ),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('custom_notes')
    # ### end Alembic commands ###
