"""bad login time stamp

Revision ID: f631fdb39597
Revises: f9cabb89eb81
Create Date: 2020-10-16 20:37:18.333023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f631fdb39597'
down_revision = 'f9cabb89eb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_attempt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_attempt')
    # ### end Alembic commands ###
