"""bad logins

Revision ID: f9cabb89eb81
Revises: 6487e95086fe
Create Date: 2020-10-16 20:12:38.563611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cabb89eb81'
down_revision = '6487e95086fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_login_attempt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_count')
    sa.Column('Id1', sa.INTEGER(), nullable=True),
    sa.Column('Frequency1', sa.INTEGER(), nullable=True),
    sa.Column('Kanji1', sa.TEXT(), nullable=True),
    sa.Column('Type1', sa.TEXT(), nullable=True),
    sa.Column('Meaning1', sa.TEXT(), nullable=True),
    sa.Column('Meaning2', sa.TEXT(), nullable=True),
    sa.Column('Meaning3', sa.TEXT(), nullable=True),
    sa.Column('Bushu1', sa.TEXT(), nullable=True),
    sa.Column('Bushu2', sa.TEXT(), nullable=True),
    sa.Column('Bushu3', sa.TEXT(), nullable=True),
    sa.Column('Bushu4', sa.TEXT(), nullable=True),
    sa.Column('Radical1', sa.TEXT(), nullable=True),
    sa.Column('Radical2', sa.TEXT(), nullable=True),
    sa.Column('Radical3', sa.TEXT(), nullable=True),
    sa.Column('Radical4', sa.TEXT(), nullable=True),
    sa.Column('Onyomi Reading1', sa.TEXT(), nullable=True),
    sa.Column('Onyomi Reading2', sa.TEXT(), nullable=True),
    sa.Column('Kunyomi Reading1', sa.TEXT(), nullable=True),
    sa.Column('Kunyomi Reading2', sa.TEXT(), nullable=True),
    sa.Column('Mnemonic', sa.TEXT(), nullable=True),
    sa.Column('Notes', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
